#version: '3.5'
  services:
    postgres:
        environment:
            - POSTGRES_PASSWORD=s3cr3t
        volumes:
            - vipdb:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d/
        image: postgres
    backend:
      build: .
      ports:
        - 80
    frontend:
      image: cmd.cat/curl/dig/ifconfig/psql
      command: sleep 9999

  volumes:
    vipdb: